package com.wide.common.model;

import com.wide.common.model.base.BaseBespeakexam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bespeakexam extends BaseBespeakexam<Bespeakexam> {
	public static final Bespeakexam dao = new Bespeakexam();
}
