package com.wide.common.model;

import com.jfinal.kit.StrKit;
import com.wide.common.model.base.BaseBespeakexam;
import com.wide.common.model.query.QueryBespeak;
import com.wide.common.model.query.QueryError;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bespeakexam extends BaseBespeakexam<Bespeakexam> {
	public static final Bespeakexam dao = new Bespeakexam();

	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryBespeak qb) {
		// TODO Auto-generated method stub
		String select = "select t.id,t1.title,t1.itembank_id,t1.questionanswer,t1.info,t1.questionanswerinfo,t.question_id";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_error t,sys_questions t1 ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(qb));
	    sqlExceptSelect.append(orderbyQuery(qb));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryBespeak qb){
		String where=" where 1=1 and t1.id=t.question_id  ";
		
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryBespeak qb){
		String orderby = " order by t.create_date desc ";
		return orderby;
		
	}
}
