package com.wide.common.model;

import com.wide.common.model.base.BaseCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Case extends BaseCase<Case> {
	public static final Case dao = new Case();
}
