package com.wide.common.model;

import com.jfinal.kit.StrKit;
import com.wide.common.model.base.BaseCurriculum;
import com.wide.common.model.query.QueryCase;
import com.wide.common.model.query.QueryCurriculum;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Curriculum extends BaseCurriculum<Curriculum> {
	public static final Curriculum dao = new Curriculum();

	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryCurriculum queryCurriculum) {
		// TODO Auto-generated method stub
		  String select = "select id,coursename,coursetitle,courselabel,courseleaturer,coursematerial,courseinfo ";
		    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_curriculum ");
		    /**
		    if (search!=null&&!search.equals("")) {
		        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
		        parameters.add("%" + search + "%");
		        parameters.add("%" + search + "%");
		    } 
		     **/
		    sqlExceptSelect.append(whereQuery(queryCurriculum));
		    sqlExceptSelect.append(orderbyQuery(queryCurriculum));
		    
		    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
		}
		/**
		 * query where查询
		 * 
		 * */
		private String whereQuery(QueryCurriculum queryCurriculum){
			String where=" where 1=1  and isdel = 0 ";
			if(StrKit.notBlank(queryCurriculum.getCoursename())){
				where += " and coursename like '%"+queryCurriculum.getCoursename()+"%'";
			}
			if(StrKit.notBlank(queryCurriculum.getCoursetitle())){
				where  +=" and coursetitle like '%"+queryCurriculum.getCoursetitle()+"%'";
			}
			
			return where;
			
		}
		/**
		 * query order by 
		 * 
		 * */
		private String orderbyQuery(QueryCurriculum queryCurriculum){
			String orderby = " order by create_date desc ";
			return orderby;
			
		}
}
