package com.wide.common.model;

import com.wide.common.model.base.BaseError;
import com.wide.common.model.query.QueryError;
import com.wide.util.TypeChecker;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Error extends BaseError<Error> {
	public static final Error dao = new Error();

	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryError qe) {
		// TODO Auto-generated method stub
		// TODO Auto-generated method stub
	    String select = "select t.id,t1.title,t1.itembank_id,t1.questionanswer,t1.info,t1.questionanswerinfo,t.question_id";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_error t,sys_questions t1 ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(qe));
	    sqlExceptSelect.append(orderbyQuery(qe));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryError qe){
		String where=" where 1=1 and t1.id=t.question_id  ";
		if(!TypeChecker.isEmpty(qe.getQuestiontype())){
			where = where + " and t1.questiontype = '"+qe.getQuestiontype()+"'";
		}
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryError qe){
		String orderby = " order by t.create_date desc ";
		return orderby;
		
	}
}
