package com.wide.common.model;

import com.wide.common.model.base.BaseError;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Error extends BaseError<Error> {
	public static final Error dao = new Error();
}
