package com.wide.common.model;

import com.wide.common.model.base.BaseExampapers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exampapers extends BaseExampapers<Exampapers> {
	public static final Exampapers dao = new Exampapers();
}
