package com.wide.common.model;

import com.wide.common.model.base.BaseExampapersQtypes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExampapersQtypes extends BaseExampapersQtypes<ExampapersQtypes> {
	public static final ExampapersQtypes dao = new ExampapersQtypes();
}
