package com.wide.common.model;

import com.wide.common.model.base.BaseExamAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamAnswer extends BaseExamAnswer<ExamAnswer> {
	public static final ExamAnswer dao = new ExamAnswer();
}
