package com.wide.common.model;

import com.wide.common.model.base.BaseExampapersQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExampapersQuestion extends BaseExampapersQuestion<ExampapersQuestion> {
	public static final ExampapersQuestion dao = new ExampapersQuestion();
}
