package com.wide.common.model;

import com.wide.common.model.base.BaseExaminee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Examinee extends BaseExaminee<Examinee> {
	public static final Examinee dao = new Examinee();
}
