package com.wide.common.model;

import com.wide.common.model.base.BaseExercise;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Exercise extends BaseExercise<Exercise> {
	public static final Exercise dao = new Exercise();
}
