package com.wide.common.model;

import com.wide.common.model.base.BaseItembank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Itembank extends BaseItembank<Itembank> {
	public static final Itembank dao = new Itembank();
}
