package com.wide.common.model;

import com.wide.common.model.base.BaseQuestions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questions extends BaseQuestions<Questions> {
	public static final Questions dao = new Questions();
}
