package com.wide.common.model;

import com.wide.common.model.base.BaseQuestionoptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Questionoptions extends BaseQuestionoptions<Questionoptions> {
	public static final Questionoptions dao = new Questionoptions();
}
