package com.wide.common.model;

import com.wide.common.model.base.BaseSubject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Subject extends BaseSubject<Subject> {
	public static final Subject dao = new Subject();
}
