package com.wide.common.model;

import com.jfinal.kit.StrKit;
import com.wide.common.model.base.BaseTextbook;
import com.wide.common.model.query.QueryCase;
import com.wide.viewmodel.DataTablesModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Textbook extends BaseTextbook<Textbook> {
	public static final Textbook dao = new Textbook();
	@SuppressWarnings("rawtypes")
	public DataTablesModel pageDataTables(int pageNum, int pageSize, QueryCase queryCase) {
		// TODO Auto-generated method stub
	    String select = "select id,textbookname,code,editorinchief,textbookurl,issuedate,isenable";
	    StringBuilder sqlExceptSelect = new StringBuilder(" from sys_textbook ");
	    /**
	    if (search!=null&&!search.equals("")) {
	        sqlExceptSelect.append(" AND (b.title like ? or b.content like ? )");
	        parameters.add("%" + search + "%");
	        parameters.add("%" + search + "%");
	    } 
	     **/
	    sqlExceptSelect.append(whereQuery(queryCase));
	    sqlExceptSelect.append(orderbyQuery(queryCase));
	    
	    return this.paginateDataTables(pageNum, pageSize, select, sqlExceptSelect.toString());
	}
	/**
	 * query where查询
	 * 
	 * */
	private String whereQuery(QueryCase query){
		String where=" where 1=1  and isdel = 0 ";
		if(query.getName()!=null&&!query.getName().equals("")){
			where += " and textbookname like '%"+query.getName()+"%'";
		}
		if(StrKit.notBlank(query.getCode())){
			where  +=" and code like '%"+query.getCode()+"%'";
		}
		
		return where;
		
	}
	/**
	 * query order by 
	 * 
	 * */
	private String orderbyQuery(QueryCase query){
		String orderby = " order by create_date desc ";
		return orderby;
		
	}
}
