package com.wide.common.model;

import com.wide.common.model.base.BaseUserTrain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTrain extends BaseUserTrain<UserTrain> {
	public static final UserTrain dao = new UserTrain();
}
