package com.wide.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.wide.config.DbModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrain<M extends BaseTrain<M>> extends DbModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTrainname(java.lang.String trainname) {
		set("trainname", trainname);
	}

	public java.lang.String getTrainname() {
		return get("trainname");
	}

	public void setTrainstarttime(java.util.Date trainstarttime) {
		set("trainstarttime", trainstarttime);
	}

	public java.util.Date getTrainstarttime() {
		return get("trainstarttime");
	}

	public void setTrainendtime(java.util.Date trainendtime) {
		set("trainendtime", trainendtime);
	}

	public java.util.Date getTrainendtime() {
		return get("trainendtime");
	}

	public void setTraininfo(java.lang.String traininfo) {
		set("traininfo", traininfo);
	}

	public java.lang.String getTraininfo() {
		return get("traininfo");
	}

	public void setCreatorId(java.lang.String creatorId) {
		set("creator_id", creatorId);
	}

	public java.lang.String getCreatorId() {
		return get("creator_id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIsenable(java.lang.Integer isenable) {
		set("isenable", isenable);
	}

	public java.lang.Integer getIsenable() {
		return get("isenable");
	}

	public void setIsdel(java.lang.Integer isdel) {
		set("isdel", isdel);
	}

	public java.lang.Integer getIsdel() {
		return get("isdel");
	}

	public void setCurriculumId(java.lang.String curriculumId) {
		set("curriculum_id", curriculumId);
	}

	public java.lang.String getCurriculumId() {
		return get("curriculum_id");
	}

}
